  # Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: klanoshi5
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

# to run docker container by command, use : docker run --name postgres -e POSTGRES_PASSWORD=klanoshi5 -d postgres